[tcp_subject_selection]
# fmri_dir = "/Users/ipeglin/Documents"
tcp_dir = "/Users/ipeglin/Git/ds005237"
tcp_annex_remote = "9cee7da3-a848-4b59-b8ff-d7848f2ad864"
output_dir = "/Users/ipeglin/Documents/preprocessing/tcp"
filter = ["available_demos_filter", "available_shaps_filter"]
dry_run = false
